services:
  postgres:
    image: postgres:13
    container_name: guildchat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guildchat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
