
-- Messages belong to a conversation, not to a room or a DM. Both are rows in
-- conversations, so every query below works for either with no branching.
--
-- Ordering rides on the BIGSERIAL rather than created_at: ids are monotonic, so
-- "newer than" is just a larger id, and two messages sharing a timestamp cannot
-- break pagination.
--
-- client_msg_id is generated by the client and is nullable, because Postgres
-- treats NULLs as distinct in a unique constraint. Any number of messages
-- without one coexist, and a client that sends one gets retry safety: the same
-- id twice updates nothing instead of writing a second row.


CREATE TABLE messages (
  id BIGSERIAL PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL ,
  body TEXT NOT NULL ,
  client_msg_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  edited_at TIMESTAMPTZ,


  CONSTRAINT fk_messages_conversation_id
    FOREIGN KEY (conversation_id)
    REFERENCES conversations (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_messages_sender_id
    FOREIGN KEY (sender_id)
    REFERENCES users (id)
    ON DELETE CASCADE,

  CONSTRAINT messages_body_not_blank
    CHECK (length(trim(body)) > 0 AND length(body) <= 4000),

  CONSTRAINT messages_client_msg_id_unique
    UNIQUE (conversation_id , sender_id , client_msg_id)

);
