package dto

import "time"

// SendMessageRequest is the body of POST /conversations/:id/messages.
//
// ClientMsgID is optional and generated by the client with crypto.randomUUID().
// Sending one makes the request idempotent: a retry after a dropped connection
// returns the message that already exists instead of posting a second copy. It
// is also what lets the sender's own UI match an optimistically rendered
// message against the confirmed one, which the server id cannot do because the
// optimistic copy does not have one yet.

type SendMessageRequest struct {
	Body        string  `json:"body" binding:"required,min=1,max=4000"`
	ClientMsgID *string `json:"client_msg_id" binding:"omitempty,uuid"`
}

// MessageResponse is one message on the wire. This exact shape is what the
// list endpoint returns and what the socket will push later, so a client
// parses and renders a message in one place regardless of how it arrived.

type MessageResponse struct {
	ID             int64        `json:"id"`
	ConversationID int64        `json:"conversation_id"`
	Sender         UserResponse `json:"sender"`
	Body           string       `json:"body"`
	ClientMsgID    *string      `json:"client_msg_id,omitempty"`
	CreatedAt      time.Time    `json:"created_at"`
	EditedAt       *time.Time   `json:"edited_at,omitempty"`
}

/*
	ListMessagesQuery is the queyr string of GET /conversations/:id/messages.

	The `form` tags are the what ShouldBindQuery reads ; `json` tas would do nothing
	here, since onone of this arrives in a body

	Limit is a plain int rather a pointer: zero means "not sent" , and the service turns that in the default , the max is enforced here so an absurd
	page size is rejected before it reaches the database.

*/

type ListMessagesQuery struct {
	Before *int64 `form:"before" binding:"omitempty,min=1"`
	Limit  int    `form:"limit" binding:"omitempty,min=1,max=100"`
}

/*
	ListMessagesResponse is one page on the wire

	Messages are newset first, matching the order of the index stores them in. A
	client rendering a chat revrses them; a client catching up after a
	disconnect wants them in this order anyway.
*/

type ListMessagesResponse struct {
	Messages []MessageResponse `json:"messages"`

	NextCursor *int64 `json:"next_cursor,omitempty"`

	HasMore bool `json:"has_more"`
}
